"""Rotating topic pool for daily cat & rabbit comedy video generation."""

TOPICS = [
    "a cat and rabbit dance-off in the garden",
    "a rabbit steals the cat's favorite nap spot",
    "a cat chases a rabbit through a maze of hedges",
    "a rabbit outsmarts a cat with a clever trick",
    "a cat and rabbit race through the neighborhood",
    "a cat tries to catch a rabbit's shadow",
    "a rabbit and cat get into a silly food fight",
    "a cat slips on a banana peel chasing a rabbit",
    "a rabbit teaches a cat a new dance move",
    "a cat and rabbit compete in a talent show",
    "a rabbit hides in increasingly silly places from a cat",
    "a cat and rabbit build a blanket fort together",
    "a rabbit accidentally bumps into a cat's tower of yarn",
    "a cat and rabbit have a snowball fight",
    "a rabbit challenges a cat to a hopping contest",
    "a cat gets tangled in yarn while chasing a rabbit",
    "a rabbit and cat discover a mysterious box together",
    "a cat tries to sneak up on a rabbit and fails hilariously",
    "a rabbit and cat have a silly staring contest",
    "a cat chases a laser pointer into a rabbit's garden",
    "a rabbit and cat team up to reach a high shelf",
    "a cat and rabbit get soaked in a surprise rain shower",
    "a rabbit bounces a cat off a trampoline by accident",
    "a cat and rabbit have a tug of war over a toy",
    "a rabbit disguises itself to trick a chasing cat",
    "a cat and rabbit accidentally swap hats and get confused",
    "a rabbit leads a cat on a wild goose chase through the yard",
    "a cat and rabbit have a dance battle in the rain",
    "a rabbit surprises a napping cat with a splash",
    "a cat and rabbit become best friends after a funny mishap",
]
