"""Rotating topic pool for daily cartoon video generation."""

TOPICS = [
    "why sharing toys is fun",
    "why sleep matters",
    "trying new foods for the first time",
    "why brushing your teeth is important",
    "being kind to a new friend",
    "why exercise makes you strong",
    "what to do when you feel scared",
    "the importance of saying sorry",
    "why teamwork makes everything easier",
    "being patient while waiting your turn",
    "why washing your hands matters",
    "the fun of trying something new",
    "why it's okay to make mistakes",
    "helping a friend who is sad",
    "why listening to others is important",
    "the joy of a rainy day adventure",
    "why cleaning up your toys matters",
    "being brave on the first day of school",
    "why saying thank you feels good",
    "a fun day at the park",
    "a superhero training day",
    "a pretend water balloon battle",
    "an obstacle course challenge between friends",
    "a silly dance contest",
    "a bike race adventure",
    "a hide and seek adventure in the garden",
    "a treasure hunt in the forest",
    "a cooking adventure with fruit friends",
    "a camping trip under the stars",
    "a rainy day indoor games adventure",
]
