"""Rotating topic pool for daily video generation. Each entry pairs a topic with its
content type so the story always matches the right cast of characters."""

TOPICS = [
    {"topic": "a cat and rabbit dance-off in the garden", "type": "animals"},
    {"topic": "a rabbit steals the cat's favorite nap spot", "type": "animals"},
    {"topic": "a cat chases a rabbit through a maze of hedges", "type": "animals"},
    {"topic": "a rabbit outsmarts a cat with a clever trick", "type": "animals"},
    {"topic": "a cat and rabbit race through the neighborhood", "type": "animals"},
    {"topic": "a cat tries to catch a rabbit's shadow", "type": "animals"},
    {"topic": "a rabbit and cat get into a silly food fight", "type": "animals"},
    {"topic": "a cat slips on a banana peel chasing a rabbit", "type": "animals"},
    {"topic": "a rabbit teaches a cat a new dance move", "type": "animals"},
    {"topic": "a cat and rabbit compete in a talent show", "type": "animals"},
    {"topic": "a rabbit hides in increasingly silly places from a cat", "type": "animals"},
    {"topic": "a cat and rabbit build a blanket fort together", "type": "animals"},
    {"topic": "a rabbit accidentally bumps into a cat's tower of yarn", "type": "animals"},
    {"topic": "a cat and rabbit have a snowball fight", "type": "animals"},
    {"topic": "a rabbit challenges a cat to a hopping contest", "type": "animals"},
    {"topic": "a cat gets tangled in yarn while chasing a rabbit", "type": "animals"},
    {"topic": "a rabbit and cat discover a mysterious box together", "type": "animals"},
    {"topic": "a cat tries to sneak up on a rabbit and fails hilariously", "type": "animals"},
    {"topic": "a rabbit and cat have a silly staring contest", "type": "animals"},
    {"topic": "a cat chases a laser pointer into a rabbit's garden", "type": "animals"},
    {"topic": "a rabbit and cat team up to reach a high shelf", "type": "animals"},
    {"topic": "a cat and rabbit get soaked in a surprise rain shower", "type": "animals"},
    {"topic": "a rabbit bounces a cat off a trampoline by accident", "type": "animals"},
    {"topic": "a cat and rabbit have a tug of war over a toy", "type": "animals"},
    {"topic": "a rabbit disguises itself to trick a chasing cat", "type": "animals"},
    {"topic": "a cat and rabbit accidentally swap hats and get confused", "type": "animals"},
    {"topic": "a rabbit leads a cat on a wild goose chase through the yard", "type": "animals"},
    {"topic": "a cat and rabbit have a dance battle in the rain", "type": "animals"},
    {"topic": "a rabbit surprises a napping cat with a splash", "type": "animals"},
    {"topic": "a cat and rabbit become best friends after a funny mishap", "type": "animals"},
    {"topic": "an elephant and children journey across the savanna to find sweet mangoes", "type": "journey"},
    {"topic": "an elephant leads children through the jungle searching for ripe fruit", "type": "journey"},
    {"topic": "children and a baby elephant climb a hill to reach a fruit orchard", "type": "journey"},
    {"topic": "an elephant and children cross a river to find a hidden fruit grove", "type": "journey"},
    {"topic": "children help an elephant find fruit, then throw a feast for the whole village", "type": "journey"},
    {"topic": "an elephant and children get lost looking for fruit but find a wonderful surprise", "type": "journey"},
    {"topic": "an elephant carries children on an adventure to gather fruit for a festival", "type": "journey"},
]
